#应用程序名
spring:
  application:
    name: eureka-feign-client
#上传链路信息的服务器地址
  zipkin:
    base-url: http://localhost:9411
#以100%的概率将链路的数据上传给ZipKin Server
  sleuth:
    sampler:
      percentage: 1.0
#端口
server:
  port: 8765
#服务注册地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#开启Hystrix熔断器功能
feign:
  hystrix:
    enabled: true

#日志文件      
logging:
  file: "logs/eureka-client-feign.log"

endpoints:
  health:
    sensitive: false
    enabled: true
  actuator:
    enabled: true
    sensitive: false
  beans:
    sensitive: false
    enabled: true

#关闭Actuator安全验证
management:
  security:
    enabled: false
