#日志输出路径
logging:
  file: "logs/boot-admin-sample.log"
#应用程序名
spring:
  application:
    name: service-admin
#spring boot admin 默认开启的节点
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti
      turbine:
        clusters: default
        location: service-turbine
#服务注册地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.10.182.11:8761/serviceregistry/eureka/
  instance:
    metadata-map:
      user.name: admin
      user.password: 123456


endpoints:
  health:
    sensitive: false
    enabled: true
  actuator:
    enabled: true
    sensitive: false
  beans:
    sensitive: false
    enabled: true
#关闭Actuator安全验证
management:
  security:
    enabled: false
#端口
server:
  context-path: /admin
  port: 5001
#关闭基本身份验证
security.basic.enabled: false
#配置Security用户名和密码
security:
  user:
    name: admin
    password: 123456


